### ISSUE TITLE
Serialization broken

### ISSUE THREAD

**Issue by FDMX2** [AndresTraks/BulletSharpPInvoke#11]
Hi,

the SerializeDemo demo works correctly with different *.bullet files (like the given testFile.bullet with the falling fragmented donut in it). So deserialization works as expected. 
Running the demo without a *.bullet file, creates the scene correct, but the serialization leads to a corrupt file. 
Opening the created file with <a href="https://code.google.com/p/gamekit/downloads/detail?name=FileInspector-Win32-749.zip&can=2&q="> FileInspector</a> only shows many empty PointerArrays.

**Comment by AndresTraks** [comment]
To simplify internal object management logic, the serialization and deserialization code was rewritten in C#, but it's not quite done yet.

I think I got stuck precisely because the file format is really complicated and I was missing such a useful tool as FileInspector. I'll look at it later today. It should start working once this line is implemented:
https://github.com/AndresTraks/BulletSharpPInvoke/blob/b7ca05ce0240af2e747d4de12500cae6e9ca1407/BulletSharpPInvoke/LinearMath/Serializer.cs#L376

Currently any chunk in a serialized file is treated as a PointerArray since the DnaNr is left as 0, which is the ID for a PointerArray.

**Comment by AndresTraks** [comment]
Probably needs more testing, but seems to work now.
