### ISSUE TITLE
No demo code documentation.

### ISSUE THREAD

**Issue by JonRurka** [AndresTraks/BulletSharpPInvoke#23]
Why is there practically no documentation for the demo code? This is suppose to be learning/review material.

**Comment by AndresTraks** [comment]
The demo code is based on Bullet examples that also have very little documentation.
Documentation has always been a weak point for Bullet. The problem is that only a few people are working on Bullet and only one working on BulletSharp, so documentation is going to be less of a priority than working demo code.
You might have better luck reporting this for Bullet, even though there's already an API documentation request open since 2008:
https://github.com/bulletphysics/bullet3/issues/152

**Comment by JonRurka** [comment]
ok, I see your point. but could you answer me this; is FreeLook.Target supposed to be a point the camera is looking at directly at?

**Comment by AndresTraks** [comment]
Yes, that's right.

**Comment by JonRurka** [comment]
Also, a little unrelated, but I have another issue. I cannot compile the demo projects. It fails in OpenTK with "error MSB3030: Could not copy the file "app.config" because it was not found."

EDIT: fixed that, but am unable to find "settings.xml" required by the demo projects.

**Comment by JonRurka** [comment]
I must ask; why was it necessary to implement FIVE graphics libraries into the demo projects of a physics engine? Only one of the OpenGL libraries would have been sufficient. The rest just drastically over complicate the project.

also, can libbulletc be built to 64 bit?

**Comment by AndresTraks** [comment]
I found missing config files in the OpenTK project and added them. Thanks!

The SharpDX project for Direct3D 10 was removed some time ago.

**Comment by AndresTraks** [comment]
I started with SlimDX, because I was familiar with it. Then I added SharpDX out of personal interest. OpenTK was added to support Linux/BSD and Mono. I think there's some useful utility code that can be used to get started on different graphics platforms. It's interesting to note that SharpDX has better performance than OpenTK, but I'm not sure if it's because SharpDX is better optimized or because my code isn't optimal.

libbulletc can be built as 64-bit by selecting a 64-bit generator in CMake:
https://github.com/AndresTraks/BulletSharpPInvoke/wiki/Build-Instructions

Or use the prebuilt binaries.

**Comment by JonRurka** [comment]
I can't seem to find 64 bit pre-built binaries for BulletSharpPInvoke, and I get this error when trying to build it as 64 bit in visual studio: fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'. Looking at the properties, none of the modules referenced by libbulletc have the "Linker" properties except for libbulletc itself.

Thanks!

EDIT: Issue solved, got it to build to 64 bit.
