### ISSUE TITLE
BvhTriangleMeshShape not disposing properly

### ISSUE THREAD

**Issue by JonRurka** [AndresTraks/BulletSharpPInvoke#24]
When creating a BvhTriangleMeshShape and casting it to a CollisionShape, calling Dispose on the CollisionShape does not dispose the BvhTriangleMeshShape's MeshInterface. you need cast it back to a BvhTriangleMeshShape  then call Dispose on that.

**Comment by JonRurka** [comment]
I'm still getting System.AccessViolationException errors when creating new BvhTriangleMeshShape objects after disposing a previous one. Happens on the `BvhTriangleMeshShape.btBvhTriangleMeshShape_new(IntPtr meshInterface, bool useQuantizedAabbCompression)` method.

EDIT: no dispose method at all in BvhTriangleMeshShape, so need to Dispose MeshInterface directly. still get access violation, however.

**Comment by AndresTraks** [comment]
BvhTriangleMeshShape shouldn't dispose the mesh interface, because it didn't create it and therefore doesn't own it. BvhTriangleMeshShape just keeps a reference to the mesh interface that is passed to it in the constructor. The mesh interface should be disposed separately. For example, like the way you described it.

I haven't checked the demos, but probably they don't explicitly dispose the mesh interface, which should be looked at. Well, at least it'll get implicitly collected.

Not sure about the AccessViolationException. You could compile a debug version of libbulletc and [enable debugging of unmanaged code](https://msdn.microsoft.com/en-us/library/tdw0c6sf(v=vs.100).aspx) to see where exactly it happens.

**Comment by JonRurka** [comment]
The access violation happens in btStridingMeshInterface.cpp on line 69.

Call stack: http://i.imgur.com/yLHjcfe.png

**Comment by JonRurka** [comment]
So far what I can tell it's coming from `graphicsbase[0]` in `triangle[1].setValue`.

**Comment by AndresTraks** [comment]
Check that the vertex and index strides of the mesh interface are correct and that the vertex and index buffers are of the right size. You could post the code too.

**Comment by JonRurka** [comment]
https://gist.github.com/nug700/8c923deeb704b068809f37d2850cbdb8

After adding mesh.Dispose to the Dispose function, I haven't gotten the access violation (it didn't happen every time before, though). Slightly unrelated but I do, however, trigger a breakpoint in the native code when calculating the local intertia, with a comment saying moving concave objects for btTriangleMeshShape shapes is not supported. How do I create concave shapes that can be moved?

**Comment by AndresTraks** [comment]
You can make moving concave shapes using GImpactMeshShape or even better, do convex decomposition (HACD) and combine convex shapes into a compound concave shape.
