### ISSUE TITLE
CMake crash when trying to generate solution for libbulletc

### ISSUE THREAD

**Issue by Krakean** [AndresTraks/BulletSharpPInvoke#39]
Here is the video:
https://dl.dropboxusercontent.com/s/1zeyxal3nwcmo5t/2018-01-28_22-19-29.mp4

Crash happens on CMake 3.9.6 and CMake 3.10.2
Visual Studio 2017 also cant open CMake lists when using a feature "Open from Folder"

Update: seems like something wrong with CMakeLists.txt when binary folder is set:
https://i.imgur.com/qTEPsWA.png (take a look at path...)
Heh. Its created so many "bullet" subfolders so I even can't delete root folder :)

**Comment by Krakean** [comment]
Removing this line frrom CMakeLists.txt:
ADD_SUBDIRECTORY("${BULLET_INCLUDE_DIR}/.." "${CMAKE_CURRENT_BINARY_DIR}/bullet")

solves the problem with CMake crash.

**Comment by AndresTraks** [comment]
The CMake script looks for Bullet in the locations defined in the "FIND_PATH(BULLET_INCLUDE_DIR..." block.
Since Bullet is in an unexpected folder (../../BulletSDK), the script is not able to find it. For example, the [build instructions](https://github.com/AndresTraks/BulletSharpPInvoke/wiki/Build-Instructions) specify using ../../bullet3.
The fact that CMake crashes because of this is a bug in CMake.
You can either rename the BulletSDK folder to bullet3 or add "${PROJECT_SOURCE_DIR}/../BulletSDK/src/" to the FIND_PATH block.

**Comment by Krakean** [comment]
Thanks Andres, it helped
