### ISSUE TITLE
libbulletc compile error

### ISSUE THREAD

**Issue by CornLizard** [AndresTraks/BulletSharpPInvoke#65]
Hello, I tried to compile libbulletc and I get the following error. I'm unsure of how to continue. Any help would be highly appreciated.

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C2039	'setCachedSeperatingAxis': is not a member of 'btGjkPairDetector'	libbulletc	E:\Github\BulletSharpPInvoke\libbulletc\src\btGjkPairDetector_wrap.cpp	67		

Also, there is a linker error.

Severity Code Description Project File Line Suppression State Suppression State
Error LNK1104 cannot open file '..\lib\Debug\libbulletc_Debug.lib' bulletctest E:\Github\BulletSharpPInvoke\libbulletc\test\LINK 1

**Comment by MetaCitizenOffical** [comment]
Also there is a linker error

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	LNK1104	cannot open file '..\lib\Debug\libbulletc_Debug.lib'	bulletctest	E:\Company\Github\BulletSharpPInvoke\libbulletc\test\LINK	1

**Comment by AndresTraks** [comment]
The typo was fixed in bullet: https://github.com/bulletphysics/bullet3/commit/133fd3a73cc4e93c98d84cb32cc4d0918dbcbfaf
I'll update libbulletc probably today.

You can change "setCachedSeperatingAxis" -> "setCachedSeparatingAxis" in btGjkPairDetector_wrap.cpp /btGjkPairDetector_wrap.h and it should work.

**Comment by CornLizard** [comment]
Thank you very much :) It now compiles no problem!
