### ISSUE TITLE
Unable to compule bulletsharpgen

### ISSUE THREAD

**Issue by publicENEMY** [AndresTraks/BulletSharpPInvoke#7]
i can compile bulletsharppinvoke, but unable to compile bulletsharpgen and libbulletc.

here are the bulletsharpgen errors

Error   1   Could not copy the file "e:\Users\iJam\Source\Repos\BulletSharpPInvoke\BulletSharpGen\libclang.dll" because it was not found.   BulletSharpGen

Where can i find libclang.dll?

**Comment by AndresTraks** [comment]
Go to llvm.org, All Releases, latest download link, Clang for Windows. Install the file.
You should find libclang.dll in C:\Program Files (x86)\LLVM\bin
I don't want to put it in the repository, because it's 10 MB.

The code generator is just a hack that creates only partial code (like ~85% of it). It's probably not useful to anyone but me, but who knows.
