### ISSUE TITLE
cmake falls into a (endless?) loop and creates recursive folder structure

### ISSUE THREAD

**Issue by markol4** [AndresTraks/BulletSharpPInvoke#72]
After repository is cloned and opened in Visual Studio 2019 **cmake** is started automatically and begins with **libbulletc** project processing.
Instead of finishing its work promptly, **cmake** falls into a loop and creates endless folder structure in:

libbulletc\out\build\x64-Debug (default)

After a while you can observe:

libbulletc\out\build\x64-Debug (default)\bullet\bullet\bullet\bullet\bullet\bullet\bullet\bullet\bullet\bullet........

folder structure which goes insanely deep. So deep that there is a problem to delete the structure. 

Any suggestions how to fix this?

**Comment by zorkind** [comment]
Same issue here :(

**Comment by zorkind** [comment]
So i figured out how to make it build the solution.

Download the code from here https://github.com/bulletphysics

Then open the open the CMakeLists.txt and point the ${PROJECT_SOURCE_DIR} to where you put the files.

I would recomend placing it near the libbulletc source folder, then you put how he can navigate to that folder relative to the current folder using /../ etc.

Now i can't make the library get build from Visual Studio project tho :( so 1 step forward but still stuck :(

**Comment by AndresTraks** [comment]
The libbulletc CMake script will look for the bullet3 source directory in:
	${PROJECT_SOURCE_DIR}/../../bullet/src/
	${PROJECT_SOURCE_DIR}/../bullet/src/
	${PROJECT_SOURCE_DIR}/../../bullet3/src/
	${PROJECT_SOURCE_DIR}/../bullet3/src/
If not found, CMake would create all those bullet folders into the build directory. I think it's some bug in CMake.

I added a check to make sure that the bullet3 directory is found before continuing: https://github.com/AndresTraks/BulletSharpPInvoke/commit/8f056dc289a937cdb128d6fac03fcab69efd3f2c
This gives you the chance to specify the BULLET_INCLUDE_DIR variable.

The [build instructions](https://github.com/AndresTraks/BulletSharpPInvoke/wiki/Build-Instructions) do tell you to put bullet3 and BulletSharpPInvoke in the same directory so that autodetection would work, but I'll probably change the instructions now that the check is there.

**Comment by zorkind** [comment]
Thanks Andres :)
