### ISSUE TITLE
Missing anchors for softbodies

### ISSUE THREAD

**Issue by FDMX2** [AndresTraks/BulletSharpPInvoke#9]
Hi,

I used BulletSharpGen before in my application and wanted to port it to BulletSharpPInvoke. To control softbodies i appended anchors to them. This works as demonstarted in the PInvoke Demos. But the softbody class from PInvoke doesn't have the Anchors property like the BulletSharp Version of this class. 
Looking at the PInvoke source shows there is no Implementation of an AlignedAnchorArray (corresponding to the AlignedLinkArray, AlignedFaceArray...)
The necessary functions are also missing libbulletc sources (like btAlignedSoftBodyAnchorArray_at and so on).

Is this on purpose? Will it be added in future releases?

**Comment by AndresTraks** [comment]
I just haven't got around to it and BulletSharpGen doesn't know how to generate template specializations yet. So AlignedAnchorArray should be coded manually.
I'll do it today. It should be easy since it's analogous to all the other Aligned\* classes and it's already implemented in C++/CLI. Thanks for reporting!

**Comment by AndresTraks** [comment]
It's done now.

**Comment by FDMX2** [comment]
Thank you, works like charm!
